project/apps/image_reader/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

if settings.DEBUG:
    urlpatterns += [
        url(
            r'^media/(?P<path>.*)$',
            serve, {
                'document_root': settings.MEDIA_ROOT,
            }
        ),
    ]
    urlpatterns += staticfiles_urlpatterns()

project/apps/website/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
]

if settings.DEBUG:
    urlpatterns += [
        url(
            r'^media/(?P<path>.*)$',
            serve, {
                'document_root': settings.MEDIA_ROOT,
            }
        ),
    ]
    urlpatterns += staticfiles_urlpatterns()

project/urls.py
from django.conf.urls import include, url
from django.urls import path, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    url(r'^image-reader/', include(('image_reader.urls', 'image_reader'), namespace="image_reader")),
    url(r'^website/', include(('website.urls', 'website'), namespace="website")),
]


urlpatterns += [
    url(
        r'^media/(?P<path>.*)$',
        serve, {
            'document_root': settings.MEDIA_ROOT,
        }
    ),
]
urlpatterns += staticfiles_urlpatterns()

project/apps/image_reader/views.py
from annoying.decorators import render_to
from image_reader.helpers import turn_image_into_28px_image, turn_small_image_into_array, image_as_base64
from ml_models.mnist import guess_number


@render_to("image_reader/home.html")
def home(request):
    submitted = False
    if request.method == "POST" and "picture" in request.FILES:
        submitted = True
        image = request.FILES["picture"]
        small_image = turn_image_into_28px_image(image)
        pixel_array = turn_small_image_into_array(small_image)
        number = guess_number(pixel_array)[0]
        small_image_base64 = image_as_base64(small_image)

        return {
            "submitted": submitted,
            "number": number,
            "small_image": small_image,
            "pixel_array": pixel_array,
            "small_image_base64": small_image_base64,
            "image": image,
        }

    return {
        "submitted": submitted,
    }

project/apps/website/views.py
from annoying.decorators import render_to


@render_to("website/home.html")
def home(request):
    return locals()

project/apps/image_reader/templates/image_reader/home.html
{% extends "website/base.html" %}
{% block title %}Image Reader{% endblock %}
{% block description %}Machine-Learning reading of handwritten images.{% endblock %}
{% block css %}{{block.super}}
<style type="text/css">
    .pixel_table {
        font-family: monospace;
        text-align: center;
    }
    .input-group {
        margin: 20px auto;
    }
    .small_image {
        border: 1px solid #DDD;
        width: 280px;
        height: 280px;
        image-rendering: -moz-crisp-edges;
        image-rendering: -o-crisp-edges;
        image-rendering: -webkit-optimize-contrast;
        -ms-interpolation-mode: nearest-neighbor;
        image-rendering: pixelated;
    }
    .giant_number {
        font-size: 180px;
    }
    .container {
        margin-top: 10px;
    }
    form {
        /*display: block;*/
        /*margin: 0 auto;*/
        min-width: 300px;
        width: 50%;
        background: #EEE;
        border-radius: 10px;
        padding: 20px;
    }
    .lead {
        margin-top: 20px;
    }
    .section {
        margin-top: 40px;
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="jumbotron">
                <h1 class="display-4">Machine Learning in Action</h1>
                <p class="lead">Try out a neural network for reading numbers.</p>
            </div>
        </div>
    </div>
    {% if submitted %}
    {# The user just uploaded a file #}
    <div class="row">
        <div class="col-sm">
            <p class="lead">The neural network thinks this is a:</p>
            <div class="ml-2">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 text-center">
                        <img src="{{small_image_base64|safe}}" class="small_image" />
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 text-center">
                        <div class="giant_number">
                            {{number}}
                        </div>
                    </div>
                </div>
            </div>
            <br/><br/>

            <h2>Analysis Details:</h2>
            <p class="lead">Pixel values:</p>
            <div class="ml-2">
                <table class="pixel_table">
                    {% for r in pixel_array %}
                    <tr>{% for c in r %}<td>{{c}}</td>{% endfor %}</tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% endif %}
    <div class="row section">
        <div class="col-sm">
            <h2>{% if submitted %}Try another image{% else %}Try it out:{% endif %}</h2>
            <ol>
                <li>Write a number on a piece of paper.</li>
                <li>Click choose file below.</li>
                <li>Take a picture, centering the number</li>
                <li>Click Submit Image.</li>
                <li>A neural network will read the image and tell you what it thinks the number is.</li>
            </ol>
            
            <form method="POST" enctype="multipart/form-data" action=".">
                {% csrf_token %}
                <div class="input-group">
                    <input type="file" id="picture_file" name="picture">
                </div>
                <div class="input-group">
                    <button type="submit" class="btn btn-primary" >Submit Image</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

project/apps/website/templates/website/base.html
{% load static %}<!doctype html >
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title>{% block title %}{{ title }}{% endblock %}</title>
    <meta name="description" content="{% block description %}{{ description }}{% endblock %}">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}">
    {% block css %}
        {# Bootstrap #}
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% endblock %}
</head>
<body>
    {% block body %}
        {% block nav %}{% endblock %}
        {% block content %}{% endblock content %}
        {% block footer %}{% endblock %}
    {% endblock body %}
    {% block js %}
    {# Bootstrap JS #}
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js'>
    {% endblock %}
</body>
</html>

project/apps/website/templates/website/home.html
{% extends "website/base.html" %}
{% block title %}Home{% endblock %}
{% block description %}Welcome to my site{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm">
            <div class="jumbotron">
                <h1 class="display-4">Hello, world!</h1>
                <p class="lead">Welcome to my website. I'm just getting it set up.</p>
                <p>More to come soon.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">Image Reader</h5>
                <h6 class="card-subtitle mb-2 text-muted">Reads hand-written numbers using Machine Learning.</h6>
                <p class="card-text">Built using Keras, Tensorflow and the MNIST dataset.</p>
                <a href="{% url 'image_reader:home' %}" class="card-link">Try it out</a>
              </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}